### ISSUE TITLE
reseourcet-1.1.3 failing to build on MacOS/GHC 7.6.3

### ISSUE THREAD

**Issue by pkamenarsky** [snoyberg/conduit#188]
```
Downloading resourcet-1.1.3...
Configuring resourcet-1.1.3...
Building resourcet-1.1.3...
Preprocessing library resourcet-1.1.3...
[1 of 4] Compiling Data.Acquire.Internal ( Data/Acquire/Internal.hs, dist/build/Data/Acquire/Internal.o )

Data/Acquire/Internal.hs:116:12:
    Not in scope: type constructor or class `C.MonadMask'
Failed to install resourcet-1.1.3
cabal: Error: some packages failed to install:
resourcet-1.1.3 failed during the building phase. The exception was:
ExitFailure 1
```
